sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t dndmanager:latest

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push USER/REPO;