sudo: required

language: node_js

node_js:
  - "node"
  - "8"

services:
  - docker

before_install:
  - docker build -f Dockerfile -t dndmanager:latest .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push USER/REPO;
